---

- name: copy udev rule to add wireless interface for AP mode
  template:
    src: 'etc/udev/rules.d/90-wireless.rules.j2'
    dest: '/etc/udev/rules.d/90-wireless.rules'
    mode: '0644'

- name: reload and trigger udev rules
  command: 'udevadm {{ item }}'
  with_items:
    - 'control --reload-rules'
    - 'trigger'
  register: udev_rules_triggered
  changed_when: udev_rules_triggered.rc == 0

- name: configure dhcpcd with static IP address {{ moodlebox_ip_address | ipaddr('host') }}
  blockinfile:
    path: '/etc/dhcpcd.conf'
    block: |
      interface {{ moodlebox_wifi_ap_interface }}
      static ip_address={{ moodlebox_ip_address | ipaddr('host') }}
      nohook wpa_supplicant
  notify: restart networking

- name: update access point configuration file
  template:
    src: 'etc/hostapd/hostapd.conf.j2'
    dest: '/etc/hostapd/hostapd.conf'
    mode: '0644'
  notify: restart networking

- name: update access point settings
  lineinfile:
    path: '/etc/default/hostapd'
    regexp: '^#?DAEMON_CONF'
    line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
  notify: restart networking

- name: unmask, enable and start hostapd
  systemd:
    name: 'hostapd'
    state: 'started'
    enabled: 'yes'
    masked: 'no'

- name: update dnsmasq configuration
  template:
    src: 'etc/dnsmasq.conf.j2'
    dest: '/etc/dnsmasq.conf'
    mode: '0664'
  notify: restart networking

- name: update dnsmasq service file
  blockinfile:
    path: '/lib/systemd/system/dnsmasq.service'
    insertbefore: '^\[Install\]\s*$'
    block: |
      RestartSec=5
      Restart=on-failure
  notify: restart networking

- name: flush handlers
  meta: flush_handlers
