---

- name: install packages for AP mode
  apt:
    pkg: '{{ item }}'
    state: 'present'
    autoremove: 'yes'
  with_items:
    - 'iptables-persistent'
    - 'hostapd'
    - 'dnsmasq'
  register: access_point_mode_packages_installed
  until: access_point_mode_packages_installed is succeeded

- name: configure dhcpcd with static IP address {{ moodlebox_ip_address | ipaddr('host') }}
  blockinfile:
    path: '/etc/dhcpcd.conf'
    block: |
      interface {{ moodlebox_wifi_sta_interface }}
      # Uncomment following line to disable AP+STA mode
      # nohook wpa_supplicant

      interface {{ moodlebox_wifi_ap_interface }}
      static ip_address={{ moodlebox_ip_address | ipaddr('host') }}
      nohook wpa_supplicant
  notify: restart networking

- name: update access point configuration file
  template:
    src: 'etc/hostapd/hostapd.conf.j2'
    dest: '/etc/hostapd/hostapd.conf'
    mode: '0644'
  notify: restart networking

- name: update access point settings
  lineinfile:
    path: '/etc/default/hostapd'
    regexp: '^#?DAEMON_CONF'
    line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
  notify: restart networking

- name: unmask, enable and start hostapd
  systemd:
    name: 'hostapd'
    state: 'started'
    enabled: 'yes'
    masked: 'no'

- name: update dnsmasq configuration
  template:
    src: 'etc/dnsmasq.conf.j2'
    dest: '/etc/dnsmasq.conf'
    mode: '0664'
  notify: restart networking

- name: update dnsmasq service file
  blockinfile:
    path: '/lib/systemd/system/dnsmasq.service'
    insertbefore: '^\[Install\]\s*$'
    block: |
      RestartSec=5
      Restart=on-failure
  notify: restart networking

- name: flush handlers
  meta: flush_handlers
