---

- name: update wifi client configuration file 'wpa_supplicant.conf'
  template:
    src: 'etc/wpa_supplicant/wpa_supplicant.conf.j2'
    dest: '/etc/wpa_supplicant/wpa_supplicant.conf'
    mode: '0644'
  notify: restart networking

- name: unblock wifi, since wifi country is set
  copy:
    dest: '{{ item }}'
    content: '0'
    mode: '0644'
  with_items:
    - '/var/lib/systemd/rfkill/platform-3f300000.mmcnr:wlan'
    - '/var/lib/systemd/rfkill/platform-fe300000.mmcnr:wlan'
  notify: restart networking

- name: disable unused wpa_supplicant service
  systemd:
    name: 'wpa_supplicant'
    state: 'stopped'
    enabled: 'no'
    masked: 'no'

- name: flush handlers
  meta: flush_handlers
