---

- name: set wifi country to '{{ moodlebox_wifi_country }}'
  lineinfile:
    path: '/etc/wpa_supplicant/wpa_supplicant.conf'
    regexp: '^country='
    line: 'country={{ moodlebox_wifi_country }}'
  notify: restart networking

- name: do not disable wifi, since wifi country is set
  copy:
    dest: '{{ item }}'
    content: '0'
    mode: '0644'
  with_items:
    - '/var/lib/systemd/rfkill/platform-3f300000.mmcnr:wlan'
    - '/var/lib/systemd/rfkill/platform-fe300000.mmcnr:wlan'
  notify: restart networking

- name: disable unused wpa_supplicant service
  systemd:
    name: 'wpa_supplicant'
    state: 'stopped'
    enabled: 'no'
    masked: 'no'

- name: flush handlers
  meta: flush_handlers
