---

- name: Remove packages used only during the build
  ansible.builtin.apt:
    pkg: '{{ cleanup_packages }}'
    state: 'absent'
    purge: 'yes'
  vars:
    cleanup_packages:
      - 'python3-pymysql'
      - 'rpi-update'

- name: Clean Moodle database log tables
  ansible.builtin.command: mysql -e 'TRUNCATE TABLE {{ moodlebox_moodle_db }}.{{ item }}'
  with_items:
    - 'mdl_config_log'
    - 'mdl_logstore_standard_log'
    - 'mdl_task_log'
    - 'mdl_upgrade_log'
  when: moodledatabase_created is succeeded
  register: cleanup_moodle_db_emptied
  changed_when: cleanup_moodle_db_emptied.rc == 0

- name: Remove useless packages from cache and no longer required dependencies
  ansible.builtin.apt:
    autoremove: 'yes'
    autoclean: 'yes'
  register: cleanup_useless_packages_removed
  until: cleanup_useless_packages_removed is succeeded

- name: Stop DHCP server
  ansible.builtin.systemd:
    name: 'dnsmasq'
    state: 'stopped'

- name: Cleanup DHCP leases
  ansible.builtin.file:
    path: '/var/lib/misc/dnsmasq.leases'
    state: 'absent'

- name: Cleanup dirs and files
  ansible.builtin.include_tasks: cleandirfile.yml
  with_items:
    - '{{ moodlebox_moodle_data_dir }}/cache/cachestore_file'
    - '{{ moodlebox_moodle_data_dir }}/cache/'
    - '{{ moodlebox_moodle_data_dir }}/localcache/'
    - '{{ moodlebox_moodle_data_dir }}/temp/'
    - '{{ moodlebox_moodle_data_dir }}/trashdir/'
    - '{{ moodlebox_moodle_data_dir }}/sessions/'
    - '/var/lib/apt/lists/'
    - '/var/cache/debconf/'
    - '/tmp/'
    - '/var/tmp/'
    - '/root/.bash_history'
    - '/root/.mysql_history'
    - '/root/.nano_history'

- name: Find log files to truncate
  ansible.builtin.find:
    paths: '/var/log'
    recurse: 'yes'
  register: cleanup_log_files

- name: Empty log files
  ansible.builtin.command: 'truncate --size 0 {{ item.path }}'
  with_items:
    - '{{ cleanup_log_files.files }}'
  register: cleanup_log_files_emptied
  changed_when: cleanup_log_files_emptied.rc == 0

- name: Reboot box
  ansible.builtin.reboot:

- name: Remove ssh public keys
  ansible.builtin.file:
    path: '/root/.ssh'
    state: 'absent'
  when: moodlebox_build_type == 'release'
