---
- name: configure timely cron
  cron:
    name: '{{ item.name }}'
    minute: '{{ item.minute }}'
    job: '{{ item.job }}'
  with_items:
    - { name: 'Launch Moodle tasks', minute: '*', job: 'nice -n 10 ionice -c2 /usr/bin/php {{ moodlebox_moodle_source_dir }}/admin/cli/cron.php' }
    - { name: 'Backup cache', minute: '*/20', job: 'rsync -a --delete /var/cache/moodle/ /var/cache/moodle-cache-backup/' }

- name: configure special time cron
  cron:
    name: '{{ item.name }}'
    special_time: '{{ item.special_time }}'
    job: '{{ item.job }}'
  with_items:
    - { name: 'Restore cache', special_time: 'reboot', job: 'cp -Rpf /var/cache/moodle-cache-backup/* /var/cache/moodle/' }

- name: configure direvent
  template:
    src: 'etc/direvent.conf.j2'
    dest: '/etc/direvent.conf'
    mode: '0644'
  register: direvent_configured

- name: configure cron mailto variable to suppress warnings in log
  cronvar:
    name: MAILTO
    value: '""'
