---
- name: check if database for Moodle exists
  command: mysql -e 'SHOW DATABASES LIKE "{{ moodlebox_moodle_db }}"' -sN
  register: moodle_db_exists
  failed_when: moodle_db_exists.rc > 1
  changed_when: moodle_db_exists.rc == 0

- name: drop database for Moodle
  mysql_db:
    name: '{{ moodlebox_moodle_db }}'
    login_unix_socket: '/var/run/mysqld/mysqld.sock'
    state: 'absent'
  when: moodle_db_exists is changed

- name: remove temporary storage for Moodle cache
  mount:
    name: '{{ item.name }}'
    state: 'unmounted'
  with_items:
    - { name: '/var/cache/moodle' }
    - { name: '{{ moodlebox_moodle_data_dir }}/temp' }
    - { name: '{{ moodlebox_moodle_data_dir }}/sessions' }

- name: remove previous Moodle installation data
  file:
    path: '{{ item }}'
    state: 'absent'
  with_items:
    - '{{ moodlebox_moodle_data_dir }}'
    - '{{ moodlebox_moodle_source_dir }}/config.php'
    - '/var/cache/moodle'
    - '/var/cache/moodle-cache-backup'

- name: set default direvent configuration
  copy:
    dest: '/etc/direvent.conf'
    content: |
      # This is the configuration file for direvent. Read
      # direvent.conf(5) for more information about how to
      # fill this file.
      #
    mode: '0644'
