---

- name: reboot box
  reboot:

- name: restart networking
  systemd:
    name: 'networking'
    state: 'restarted'

- name: restart web services
  systemd:
    name: '{{ item }}'
    state: 'restarted'
    daemon_reload: 'yes'
  with_items:
    - 'nginx'
    - 'php7.4-fpm'

- name: restart direvent
  systemd:
    name: 'direvent'
    state: 'restarted'
