---

- name: Read reference RPiOS version from '/boot/firmware/issue.txt'
  ansible.builtin.slurp:
    src: '/boot/firmware/issue.txt'
  register: branding_issue_file

- name: Set 'branding_reference_version' variable
  ansible.builtin.set_fact:
    branding_reference_version: "{{ branding_issue_file['content'] | b64decode | regex_findall('^(.*)\\n') | first }}"

- name: Write version file
  ansible.builtin.template:
    src: 'etc/moodlebox-info.j2'
    dest: '/etc/{{ moodlebox_info_file }}'
    mode: '0644'

- name: Copy version file to boot partition
  ansible.builtin.copy:
    src: '/etc/{{ moodlebox_info_file }}'
    dest: '/boot/firmware/{{ moodlebox_info_file }}.txt'
    mode: '0644'
    remote_src: true

- name: Update motd
  ansible.builtin.template:
    src: 'etc/motd.j2'
    dest: '/etc/motd'
    mode: '0644'

- name: Copy ascii logo file
  ansible.builtin.copy:
    src: 'etc/moodlebox-logo.txt'
    dest: '/etc/{{ moodlebox_logo_file }}'
    mode: '0644'

- name: Copy script to display ascii logo
  ansible.builtin.template:
    src: 'etc/update-motd.d/20-logo.j2'
    dest: '/etc/update-motd.d/20-logo'
    mode: '0755'
