---

- name: Download and unarchive rpi-clone latest release
  ansible.builtin.unarchive:
    src: 'https://github.com/geerlingguy/rpi-clone/archive/refs/heads/master.tar.gz'
    dest: '/usr/local/sbin'
    remote_src: true
    exclude:
      - 'README.*'
      - 'LICENSE'
      - 'docs'
      - 'install'
      - '.github'
    extra_opts: [--strip-components=1]
    owner: 'root'
    group: 'root'
    mode: '0755'
